"""
installer_service.py — Install command and bash script generation.

Two public functions:
  get_install_command()      : returns the curl | bash command shown in the UI
  generate_install_script()  : returns the full bash script content for GET /install.sh
"""

from .server_address import normalize_server_url


# ---------------------------------------------------------------------------
# Install command (shown in browser UI)
# ---------------------------------------------------------------------------

def get_install_command(
    *,
    server: str,
    port: int,
    token: str,
    name: str,
    enable_logs: bool,
    enable_fim: bool,
    enable_metrics: bool,
) -> str:
    """
    Return the one-liner curl command the admin pastes on the target server.

    normalize_server_url() is called here so the URL is always well-formed —
    no double-port, no missing scheme.
    """
    base = normalize_server_url(server, port)
    logs_str = "true" if enable_logs else "false"
    fim_str = "true" if enable_fim else "false"
    metrics_str = "true" if enable_metrics else "false"

    return (
        f"curl -s {base}/install.sh | sudo bash -s -- "
        f"--token {token} "
        f"--server {base} "
        f"--name {name} "
        f"--logs {logs_str} "
        f"--fim {fim_str} "
        f"--metrics {metrics_str}"
    )


# ---------------------------------------------------------------------------
# Installer bash script (served at GET /install.sh)
# ---------------------------------------------------------------------------

def generate_install_script(server: str, port: int) -> str:
    """
    Return the full content of the installer bash script.

    The script is parameterised entirely via CLI flags — no hardcoded values.
    *server* and *port* are used only to derive the binary download base URL
    that is baked into the script as a default fallback; the --server flag
    passed by the curl command takes precedence at runtime.
    """
    base = normalize_server_url(server, port)

    return f"""#!/bin/bash
# =============================================================================
# OVS SIEM Agent Installer
# Generated by OVS SIEM server: {base}
# =============================================================================
set -euo pipefail

# ---------------------------------------------------------------------------
# Defaults (overridden by --flags below)
# ---------------------------------------------------------------------------
TOKEN=""
SERVER="{base}"
AGENT_NAME="ovs-agent"
ENABLE_LOGS="true"
ENABLE_FIM="false"
ENABLE_METRICS="true"

AGENT_BIN="/usr/local/bin/ovs-agent"
AGENT_CONF_DIR="/etc/ovs-agent"
AGENT_CONF="$AGENT_CONF_DIR/config.yaml"
SERVICE_FILE="/etc/systemd/system/ovs-agent.service"

# ---------------------------------------------------------------------------
# Argument parsing
# ---------------------------------------------------------------------------
while [[ $# -gt 0 ]]; do
  case "$1" in
    --token)    TOKEN="$2";       shift 2 ;;
    --server)   SERVER="$2";      shift 2 ;;
    --name)     AGENT_NAME="$2";  shift 2 ;;
    --logs)     ENABLE_LOGS="$2"; shift 2 ;;
    --fim)      ENABLE_FIM="$2";  shift 2 ;;
    --metrics)  ENABLE_METRICS="$2"; shift 2 ;;
    *) echo "Unknown argument: $1"; exit 1 ;;
  esac
done

# ---------------------------------------------------------------------------
# Pre-flight checks
# ---------------------------------------------------------------------------
if [[ $EUID -ne 0 ]]; then
  echo "Error: This installer must be run as root (use sudo)." >&2
  exit 1
fi

if ! command -v curl &>/dev/null; then
  echo "Error: curl is required but not installed. Please install curl first." >&2
  exit 1
fi

if [[ -z "$TOKEN" ]]; then
  echo "Error: --token is required." >&2
  exit 1
fi

if [[ -z "$SERVER" ]]; then
  echo "Error: --server is required." >&2
  exit 1
fi

# ---------------------------------------------------------------------------
# OS Detection for log paths
# ---------------------------------------------------------------------------
AUTH_LOG="/var/log/auth.log"
SYSLOG_PATH="/var/log/syslog"
AUDITD_LOG="/var/log/audit/audit.log"

if [[ -f /etc/os-release ]]; then
    . /etc/os-release
    OS_ID=$ID
    OS_LIKE=${{ID_LIKE:-""}}
    
    if [[ "$OS_ID" == "rocky" || "$OS_ID" == "rhel" || "$OS_ID" == "centos" || "$OS_LIKE" == *"rhel"* || "$OS_LIKE" == *"fedora"* ]]; then
        AUTH_LOG="/var/log/secure"
        SYSLOG_PATH="/var/log/messages"
    fi
fi

echo ""
echo "========================================"
echo "  OVS SIEM Agent Installer"
echo "========================================"
echo "  Server    : $SERVER"
echo "  Name      : $AGENT_NAME"
echo "  Logs      : $ENABLE_LOGS"
echo "  FIM       : $ENABLE_FIM"
echo "  Metrics   : $ENABLE_METRICS"
echo "  Auth Log  : $AUTH_LOG"
echo "  Syslog    : $SYSLOG_PATH"
echo "========================================"
echo ""

# ---------------------------------------------------------------------------
# Install Dependencies (Auditd, Rsyslog)
# ---------------------------------------------------------------------------
echo "[1/7] Checking for dependencies..."
PKGS=""
if ! command -v auditctl &>/dev/null; then PKGS="$PKGS auditd"; fi
if [[ ! -f /var/log/syslog && ! -f /var/log/messages ]]; then
  if ! command -v rsyslogd &>/dev/null; then PKGS="$PKGS rsyslog"; fi
fi

if [[ -n "$PKGS" ]]; then
  echo "    Installing missing packages: $PKGS"
  if command -v apt-get &>/dev/null; then
    apt-get update -qq && apt-get install -y $PKGS -qq
  elif command -v yum &>/dev/null; then
    yum install -y $PKGS -q
  else
    echo "Warning: Could not detect package manager to install dependencies. Please install $PKGS manually."
  fi
fi

# Ensure services are enabled and running
if command -v systemctl &>/dev/null; then
  systemctl enable auditd 2>/dev/null || true
  if command -v rsyslogd &>/dev/null; then
    systemctl enable rsyslog 2>/dev/null || true
    systemctl start rsyslog 2>/dev/null || true
  fi
fi

# Configure Auditd rules for execution logging (Required for T1059 detection)
# and systemd unit file-write watches (Required for T1543.002 persistence
# detection — without these, `linux_t1543_002_systemd_service_persistence`
# never receives the file-write event it needs and stays permanently silent
# even while systemctl enable/start execution IS being logged).
echo "    Configuring auditd rules for process execution and systemd persistence logging..."
mkdir -p /etc/audit/rules.d
cat > /etc/audit/rules.d/ovs-siem.rules <<EOF
-D
-b 8192
-f 1
--backlog_wait_time 60000
-a exit,always -F arch=b64 -S execve -k T1059
-a exit,always -F arch=b32 -S execve -k T1059
-w /etc/systemd/system/ -p wa -k T1543
-w /usr/lib/systemd/system/ -p wa -k T1543
-w /lib/systemd/system/ -p wa -k T1543
EOF

if command -v augenrules &>/dev/null; then
  augenrules --load
else
  service auditd restart || systemctl restart auditd || true
fi
echo "    Auditd configured successfully."

# ---------------------------------------------------------------------------
# Download agent binary (skip if already installed)
# ---------------------------------------------------------------------------
if [[ -f "$AGENT_BIN" ]]; then
  echo "[2/7] Agent binary already present at $AGENT_BIN — skipping download."
else
  echo "[2/7] Downloading agent binary..."
  DOWNLOAD_URL="$SERVER/downloads/ovs-agent-linux-amd64"
  curl -fSL --progress-bar -o "$AGENT_BIN" "$DOWNLOAD_URL" || {{
    echo "Error: Failed to download agent binary from $DOWNLOAD_URL" >&2
    echo "       Place the binary manually at $AGENT_BIN and re-run." >&2
    exit 1
  }}
fi
chmod +x "$AGENT_BIN"
echo "    Binary ready: $AGENT_BIN"

# ---------------------------------------------------------------------------
# Write configuration
# ---------------------------------------------------------------------------
echo "[3/7] Writing configuration..."
mkdir -p "$AGENT_CONF_DIR"
cat > "$AGENT_CONF" <<EOF
server_url: "$SERVER"
agent_name: "$AGENT_NAME"
enable_logs: $ENABLE_LOGS
enable_fim: $ENABLE_FIM
enable_metrics: $ENABLE_METRICS

log_paths:
  auth: "$AUTH_LOG"
  syslog: "$SYSLOG_PATH"
  auditd: "$AUDITD_LOG"
EOF
echo "    Config written: $AGENT_CONF"

# ---------------------------------------------------------------------------
# Register with SIEM server
# ---------------------------------------------------------------------------
echo "[4/7] Registering agent with SIEM server..."
REGISTER_URL="$SERVER/api/agents/register"

RESPONSE=$(curl -sf -X POST "$REGISTER_URL" \\
  -H "X-Agent-Token: $TOKEN" \\
  -H "Content-Type: application/json" \\
  -d "{{
    \\"hostname\\": \\"$(hostname -f 2>/dev/null || hostname)\\",
    \\"ip_address\\": \\"$(hostname -I | awk '{{print $1}}')\\",
    \\"os\\": \\"$(uname -s)\\",
    \\"arch\\": \\"$(uname -m)\\"
  }}") || {{
  echo "Error: Registration failed. Check that:" >&2
  echo "  - The server is reachable at $SERVER" >&2
  echo "  - The token is valid and not expired" >&2
  exit 1
}}

AGENT_KEY=$(echo "$RESPONSE" | grep -o '"agent_key":"[^"]*"' | cut -d'"' -f4)
if [[ -z "$AGENT_KEY" ]]; then
  echo "Error: Could not extract agent_key from registration response." >&2
  echo "Response was: $RESPONSE" >&2
  exit 1
fi

# Append agent_key to config
echo "agent_key: \\"$AGENT_KEY\\"" >> "$AGENT_CONF"
echo "    Registration successful. Agent key saved."

# ---------------------------------------------------------------------------
# Create systemd service
# ---------------------------------------------------------------------------
echo "[5/7] Creating systemd service..."
cat > "$SERVICE_FILE" <<EOF
[Unit]
Description=OVS SIEM Monitoring Agent
After=network.target
Wants=network-online.target

[Service]
Type=simple
ExecStart=$AGENT_BIN --config $AGENT_CONF
Restart=on-failure
RestartSec=10s
StandardOutput=journal
StandardError=journal
SyslogIdentifier=ovs-agent

[Install]
WantedBy=multi-user.target
EOF
echo "    Service file written: $SERVICE_FILE"

# ---------------------------------------------------------------------------
# Enable and start service
# ---------------------------------------------------------------------------
echo "[6/7] Enabling and starting ovs-agent service..."
systemctl daemon-reload
systemctl enable --now ovs-agent

# ---------------------------------------------------------------------------
# Verify
# ---------------------------------------------------------------------------
echo "[7/7] Verifying service status..."
sleep 2
if systemctl is-active --quiet ovs-agent; then
  echo ""
  echo "========================================"
  echo "  Agent installed and running!"
  echo "========================================"
  echo "  Use 'systemctl status ovs-agent' to check agent health."
  echo "  Logs: journalctl -u ovs-agent -f"
  echo "========================================"
else
  echo ""
  echo "Warning: Service may not have started correctly."
  echo "Check logs with: journalctl -u ovs-agent -n 50"
fi
"""

def generate_uninstall_script() -> str:
    """
    Return a standalone bash script to cleanly remove the agent.
    """
    return """#!/bin/bash
# =============================================================================
# OVS SIEM Agent Uninstaller
# =============================================================================
set -euo pipefail

if [[ $EUID -ne 0 ]]; then
  echo "Error: This uninstaller must be run as root (use sudo)." >&2
  exit 1
fi

echo "Uninstalling OVS SIEM Agent..."

# 1. Stop and Disable Service
if systemctl is-active --quiet ovs-agent; then
    echo "Stopping ovs-agent service..."
    systemctl stop ovs-agent
fi

if systemctl is-enabled --quiet ovs-agent 2>/dev/null; then
    echo "Disabling ovs-agent service..."
    systemctl disable ovs-agent
fi

# 2. Remove Systemd Unit
if [[ -f /etc/systemd/system/ovs-agent.service ]]; then
    echo "Removing service file..."
    rm /etc/systemd/system/ovs-agent.service
    systemctl daemon-reload
fi

# 3. Remove Binary
if [[ -f /usr/local/bin/ovs-agent ]]; then
    echo "Removing binary..."
    rm /usr/local/bin/ovs-agent
fi

# 4. Remove Configuration
if [[ -d /etc/ovs-agent ]]; then
    echo "Removing configuration directory..."
    rm -rf /etc/ovs-agent
fi

# 5. Remove Queue files
echo "Cleaning up temporary files..."
rm -f /agent_queue.jsonl
rm -f ./agent_queue.jsonl

echo ""
echo "========================================"
echo "  OVS SIEM Agent Uninstalled Successfully"
echo "========================================"
"""

def get_reinstall_command(
    *,
    server: str,
    port: int,
    token: str,
    name: str,
    enable_logs: bool,
    enable_fim: bool,
    enable_metrics: bool,
) -> str:
    """
    Returns a one-liner that uninstalls the current agent and installs it again.
    Uses the same flags as the original install command.
    """
    base = normalize_server_url(server, port)
    install_cmd = get_install_command(
        server=server,
        port=port,
        token=token,
        name=name,
        enable_logs=enable_logs,
        enable_fim=enable_fim,
        enable_metrics=enable_metrics
    )
    # Combine uninstall and install
    return f"curl -s {base}/uninstall.sh | sudo bash && {install_cmd}"
